#cloud-config

chpasswd:
  expire: false
  users:
    - {name: ubuntu, password: '123456', type: text}
    - {name: devuser, password: $6$rounds=4096$A1B2C3$T5RM2U1zM3ZV9cW6vD5ZsXNQqKnwWXYKf1FhBxXrA7aB08J6dxRy7GZ0GcTFIehO56xt0XxMPQ7ABhEVHgEAV1, type: text}
    - {name: tempuser, type: RANDOM}

ssh_pwauth: true
ssh_deletekeys: false

users:
  - name: ubuntu
    shell: /bin/bash
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: devuser
    shell: /bin/bash
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: tempuser
    shell: /bin/bash
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL